"""initial schema

Revision ID: 6692fa5a44d8
Revises: 
Create Date: 2025-12-21 09:24:03.555203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6692fa5a44d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscriptions')
    op.drop_table('stripe_events')
    op.alter_column('subscriptions', 'customer_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('subscriptions', 'subscription_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('idx_subscriptions_user_id'), table_name='subscriptions')
    op.drop_constraint(op.f('subscriptions_subscription_id_key'), 'subscriptions', type_='unique')
    op.drop_constraint(op.f('subscriptions_subscription_id_uniq'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_subscriptions_user'), 'subscriptions', type_='foreignkey')
    op.alter_column('summaries', 'tokens_used',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_summaries_created_at'), table_name='summaries')
    op.drop_index(op.f('idx_summaries_user_id'), table_name='summaries')
    op.create_index(op.f('ix_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_summaries_user_id'), table_name='summaries')
    op.create_index(op.f('idx_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    op.create_index(op.f('idx_summaries_created_at'), 'summaries', ['created_at'], unique=False)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('summaries', 'tokens_used',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_foreign_key(op.f('fk_subscriptions_user'), 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('subscriptions_subscription_id_uniq'), 'subscriptions', ['subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('subscriptions_subscription_id_key'), 'subscriptions', ['subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.alter_column('subscriptions', 'subscription_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('subscriptions', 'customer_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('stripe_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stripe_events_pkey')),
    sa.UniqueConstraint('event_id', name=op.f('stripe_events_event_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_checkout_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_subscriptions_pkey'))
    )
    # ### end Alembic commands ###
